export const EVENT_BUS = {
    LOGIN: 'EVENT_BUS_LOGIN',
    NOTIFICATION: {
        CONNECTED: 'NOTIFICATION_CONNECTED',
        START: 'NOTIFICATION_START',
        MOVE: 'NOTIFICATION_MOVE'
    }
}
