export const ROUTE_NAME = {
    HOME: 'home',
    RADAR: 'radar',
    INFO: 'info',
    INFO_DETAIL: 'info-detail',
    WARNING: 'warning',
    DATA: 'data',
    TIME: 'time',
    ICON: 'icon',
    SOCIAL: 'social',
    USER_PROFILE: 'user-profile',
    NOT_FOUND: 'not-found',
    LOGIN: 'login',
    MANAGEMENT: 'management',
    LIST_POST: 'listPost',
    CREATE_POST: 'createPost',
    EDIT_POST: 'editPost',
    DELETE_POST: 'deletePost',
    LIST_ICON: 'listIcon',
    LIST_DATA: 'listData',
    USER_INFO: 'user-info',
    SOCIAL_POST: 'social-post',
    CHANGE_PASSWORD: 'change-password',
    LIST_USER: 'list-user',
    CREATE_USER: 'createUser',
}

export const PATH = {
    RADAR: '/radar',
    INFO: '/info',
    INFO_DETAIL: '/info/:id',
    WARNING: '/warning/:categoryId/:statusId',
    DATA: '/data',
    TIME: '/time',
    ICON: '/icon',
    SOCIAL: '/social',
    NOT_FOUND: '/not-found',
    USER_PROFILE: '/user-profile',
    USER_INFO: '/user-info',
    SOCIAL_POST: '/social-post',
    CHANGE_PASSWORD: '/change-password',
    LOGIN: '/login',
    MANAGEMENT: '/management',
    ADMIN: '/admin',
    LIST_POST: 'list-post',
    CREATE_POST: 'create-post',
    EDIT_POST: 'edit-post/:id',
    DELETE_POST: 'delete-post/:id',
    LIST_ICON: 'list-icon',
    LIST_DATA: 'list-data',
    LIST_USER: 'list-user/:role',
    CREATE_USER: 'create-user/:role',
}
