export const ROUTE_NAME = {
    HOME: 'home',
    RADAR: 'radar',
    INFO: 'info',
    INFO_DETAIL: 'info-detail',
    DATA: 'data',
    TIME: 'time',
    ICON: 'icon',
    SOCIAL: 'social',
    NOT_FOUND: 'not-found',
    LOGIN: 'login',
    MANAGEMENT: 'management',
    LIST_POST: 'listPost',
    CREATE_POST: 'createPost',
    EDIT_POST: 'editPost',
    DELETE_POST: 'deletePost',
    LIST_ICON: 'listIcon',
}

export const PATH = {
    RADAR: '/radar',
    INFO: '/info',
    INFO_DETAIL: '/info/:id',
    DATA: '/data',
    TIME: '/time',
    ICON: '/icon',
    SOCIAL: '/social',
    NOT_FOUND: '/not-found',
    LOGIN: '/login',
    MANAGEMENT: '/management',
    ADMIN: '/admin',
    LIST_POST: 'list-post',
    CREATE_POST: 'create-post',
    EDIT_POST: 'edit-post/:id',
    DELETE_POST: 'delete-post/:id',
    LIST_ICON: 'list-icon'
}
