export default {
    getForecastStation: '/api/DiemDuBao/all',
    getTemperatureByStation: '/api/Temperature/get-temperature',
    getPrecipitationByStation: '/api/AmountOfRain/get-amount-of-rain',
    getWindLevelByStation: '/api/WindLevel/get-wind-level',
    getWindSpeedByStation: '/api/WindSpeed/get-wind-speed',
    getWindDirectionByStation: '/api/WindDirection/get-wind-direction',
    getHumidityByStation: '/api/Humidity/get-humidity',
    getIconWeatherByStation: '/api/Weather/get-weather',
    getMinMaxTemperatureByStation: '/api/Temperature/get-min-max-temperature',
    getMinMaxPrecipitationByStation: '/api/AmountOfRain/get-min-max-amount-of-rain',
    getMinMaxWindLevelByStation: '/api/WindLevel/get-min-max-wind-level',
    getMinMaxHumidityByStation: '/api/Humidity/get-min-max-humidity',
    getMinMaxWindSpeedByStation: '/api/WindSpeed/get-min-max-wind-speed',
}
