export default {
    createPost: "/api/Post",
    editPost: "/api/Post",
    createComment: "/api/Post/create-comment",
    approvePost: "/api/Post/approve-post/:id",
    approveComment: "/api/Post/approve-comment/:id",
    changePostStatus: "/api/Post/change-post-status/:id",
    changeCommentStatus: "/api/Post/change-comment-status/:id",
    updateComment: "/api/Post/update-comment",
    addReactionToPost: "/api/Post/add-post-action-icon",
    addReactionToComment: "/api/Post/add-comment-action-icon",
    removeReactionFromPost: "/api/Post/remove-post-action-icon/:id",
    removeReactionFromComment: "/api/Post/remove-comment-action-icon/:id",
    sharePost: "/api/Post/share",
    getListPosts: "/api/Post/get-list",
    getListPostsUser: "/api/Post/get-list-user-time-line",
    getPostById: "/api/Post/:id",
    deletePost: "/api/Post/:id",
    deleteComment: "/api/Post/comment/:id",
    getListCommentsAdmin: "/api/Post/get-list-comment",
    getListCommentsUser: "/api/Post/get-list-comment-of-user",
    getPostForApproval: "/api/Post/get-post-for-approval",
    getCommentForApproval: "/api/Post/get-comment-for-approval",
    getPostDetailForApproval: "/api/Post/get-post-detail-for-approval/:id",
    getCommentDetailForApproval: "/api/Post/get-comment-detail-for-approval/:id"
};
